name: AppointmentSystem Test
on: push
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      - name: Restore dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Build
        run: dotnet build --no-restore